AllCops:
  NewCops: enable
  SuggestExtensions: false

Lint/EmptyBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Max: 60

Metrics/ParameterLists:
  Max: 6

Style/Documentation:
  Enabled: false
